name: hydrohub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ✅ Font styling (optional)
  google_fonts: ^6.2.1

  # ✅ iOS-style icons
  cupertino_icons: ^1.0.8

  # ✅ Networking / API calls
  http: ^1.2.1
  intl: ^0.19.0

  # ✅ File & Image picker
  image_picker: ^1.0.8

  # ✅ Local storage
  shared_preferences: ^2.3.2

  # ✅ Google Maps + Geocoding + Places SDK
  google_maps_flutter: ^2.6.1
  geocoding: ^2.1.1
  flutter_google_places_sdk: ^0.3.7

  # ✅ Location services (needed for customer map detection)
  geolocator: ^13.0.1

  # ✅ Code quality / lint rules
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
